### ISSUE TITLE
Scenario tag filter does not filter scenarios

### ISSUE THREAD

**Issue by mhfrantz** [hiptest/hiptest-publisher#18]
It looks like the `--scenario-tag` filter (or the equivalent conf file setting) does add a `filter` clause to the underlying API call, but this does not actually filter the `scenario` objects returned.  Instead, test code for all scenarios are generated.  Not sure if this is a `hiptest-publisher` bug or an API bug, but I thought I'd start here.

```
Running Hiptest-publisher 0.9.5 with:
 - __cli_args: #<Set: {:config, :verbose, :filter_tags}>
 - __config_args: #<Set: {:token, :language, :framework, :output_directory, :sort, :split_scenarios, :with_folders, :scenario_tags}>
 - language: "javascript"
 - framework: "jasmine"
 - output_directory: "hiptest"
 - overriden_templates: ""
 - test_run_id: ""
 - filter_ids: ""
 - filter_tags: "client-unit"
 - tests_only: false
 - actionwords_only: false
 - actionwords_signature: false
 - actionwords_diff: false
 - aw_deleted: false
 - aw_created: false
 - aw_renamed: false
 - aw_signature_changed: false
 - with_folders: "true"
 - split_scenarios: "true"
 - leafless_export: false
 - site: "https://hiptest.net"
 - push: ""
 - push_format: "tap"
 - sort: "order"
 - verbose: true
 - config: "hiptest.conf"
 - token: "<redacted>"
 - scenario_tags: "client-unit"
URL: https://hiptest.net/publication/<redacted>/project?filter[]=tag:client-unit
[v] Fetching data from Hiptest
[v] Extracting data
[v] Analyzing data
[v] Exporting scenario ...
```

**Comment by hiptest** [comment]
Hi,

That's something we need to put back in hiptest app, but will not arrive
right now .
And we've forgotten to remove it from the publisher ;)

Cheers,
Vincent

Le jeu. 28 janv. 2016 05:08, Matt Frantz <notifications@github.com> a
écrit :

**Comment by mhfrantz** [comment]
If you are interested, I have a working implementation of this, with the caveat that it does not work if a test run ID is specified.

**Comment by daniel-kun** [comment]
I'm interested, because the scenario tag filter is an important use-case for me.

My intended use:
* Create a Test Plan "Sprint" that contains manual tests, unit tests and ui tests mixed together
* The different execution type of the test will be marked via tags
* Use hiptest-publisher with --scenario-tags=UnitTests when fetching the tests for the dev team
* Use hiptest-publisher with --scenario-tags=AutomatedUi when fetching the tests for the automated ui test team

That way the dev team, the automated ui test guy and the manual testers can share the same sprint and individually contribute their test results.

Without a functional scenario-tags filter, I'd have to create three different test plans for one sprint, which results in more fragmentation regarding test status.

**Comment by mhfrantz** [comment]
@daniel-kun We had a process similar to what you describe above.  We initially used tags to distinguish the "test tranche" (e.g. server functional, end-to-end, etc.).  The modification that I made to our fork of Hiptest Publisher was sufficient initially because we were not using test runs at all.

However, when we started to use test runs, it became apparent that the Hiptest data model (at least as reflected in the structure of the data returned by the API) did not associate tags with scenario snapshots.  That means that Hiptest does not remember (or at least does not report via the API) which tags were associated with which scenarios when the test run is synchronized.  Thus, my Hiptest Publisher hack would have to "join" the scenario snapshots to the scenarios in order to retrieve the current tags, and would not have the "snapshot" capability that make test runs so desirable.  Furthermore, the join logic would be fragile because it would rely on scenario names.

Instead, we've crafted a process around test runs.  You pointed out that you considered this approach, but were concerned with fragmentation of the test results.  We have a similar concern, but we're hoping to address the fragmentation by using the [external test runs](https://docs.hiptest.net/create-a-test-run-for-your-unit-tests/) feature.  Thus, we will generate tests using multiple test runs, but report the results using a single test run.

This is still a work in progress for us, but I'm interested in any real world use cases that are similar to our own, so we should stay in touch.  Meanwhile, I'm afraid that my change related to #18 will not help to publish tests for a test run partitioned by tags.

**Comment by vincent-psarga** [comment]
There's indeed an issue with the tags when we report them in a Test run. To explain briefly: the scenario snapshots (the copy of a scenario in a test run) is never displayed in Hiptest itself. What we use in a test run is a test snapshot (the computed test generated from the scenario) and that's were we add the tag copy when creating the test run.
With hiptest-publisher, we use the scenario snapshot to generate the code (as the test snapshot is the interpreted version and is not really useful for code generation), that's why we don't seem to have the tag when exporting from a scenario.

That's something we'll fix asap :)

**Comment by vincent-psarga** [comment]
Release 0.20 adds some filtering options when exporting:
 --filter-on-scenario-ids=1,2,3 : only export scenarios with ids 1, 2 and 3
 --filter-on-folder-ids=1,2,3: same principle with folders, exports all children of those scenarios
 --filter-on-scenario-name="My scenario": exports only "My scenario"
 --filter-on-folder-name="My folder": exports only "My folder" and all its children
 --filter-on-tags=automation:done,automation:todo: only exports scenarios and folders tagged with automation:done or automation:todo

Note that only the actionwords linked to those scenarios/folders are exported, so try not to use those options with --actionwords-signature.
