### ISSUE TITLE
Windows - ruby gem installation HTTPS error

### ISSUE THREAD

**Issue by settlersxp** [hiptest/hiptest-publisher#41]
Note: Not necessarily an error from hiptest's side, just worth mentioning in the installation guide.

When running "gem install hiptest-publisher" the following error can be encountered:

ERROR: Could not find a valid gem 'hiptest-publisher' (>= 0), here is why:
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)"

One quick fix is to:
1) gem source -a http://rubygems.org
2) gem source --remove https://rubygems.org/
3) gem install hiptest-publisher

**Comment by cbliard** [comment]
Thanks for your feedback.

Indeed there is an issue due to a change in rubygems web site certificate. The solution you propose is vulnerable to man-in-middle attacks as it does not rely on HTTPS anymore. We documented another fix here: https://github.com/hiptest/hiptest-publisher/blob/master/docs/INSTALLING/Windows.md#error-unable-to-download-data-from-httpsrubygemsorg

**Comment by cbliard** [comment]
Closing as there is no more activity. Feel free to reopen if you still encounter problems related to this issue.
